# Generated by Django 6.1.1 on 2026-09-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_brand_product_concentration_product_notes_and_more'),
        ('loyalty', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('review', 'Product Review'), ('reward', 'Reward Redemption')], default='purchase', max_length=10),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transaction', to='catalog.review'),
        ),
    ]
