# Generated by Django 6.1.1 on 2026-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_loyaltytransaction_reason_loyaltytransaction_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='When a redeemed reward was handed over.', null=True),
        ),
    ]
