# Generated by Django 6.1.1 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_redemption_fulfilled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money off a purchase when the voucher is used. 0 means the reward is collected in a boutique.', max_digits=10),
        ),
    ]
