# Generated by Django 6.1.1 on 2026-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('classic', 'Classic'), ('premium', 'Premium'), ('exotic', 'Exotic'), ('seasonal', 'Seasonal'), ('niche', 'Niche')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('image_public_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
