# Generated by Django 6.1.1 on 2026-09-15 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_city_branch_country_branch_email_and_more'),
        ('orders', '0002_order_shipping_city_order_shipping_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='App checkout retries with the same key return this order.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('customer', 'idempotency_key'), name='one_order_per_idempotency_key'),
        ),
    ]
