# Generated by Django 6.1.1 on 2026-09-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Scent notes, comma separated.', max_length=255),
        ),
    ]
