# Generated by Django 6.1.1 on 2026-09-15 09:23

from django.db import migrations, models

# Map free-text roles entered before the dropdown existed onto the choices.
ROLE_MAP = {
    "boutique manager": "boutique_manager", "manager": "boutique_manager",
    "master nose": "master_nose", "perfumer": "master_nose",
    "senior advisor": "senior_advisor",
}


def map_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(job_title=""):
        user.job_title = ROLE_MAP.get(user.job_title.strip().lower(), "sales_consultant")
        user.save(update_fields=["job_title"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_public_id_user_branch_user_job_title_and_more'),
    ]

    operations = [
        migrations.RunPython(map_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('boutique_manager', 'Boutique Manager'), ('master_nose', 'Master Nose'), ('senior_advisor', 'Senior Advisor'), ('sales_consultant', 'Sales Consultant')], max_length=30),
        ),
    ]
